### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dmitriitux** [Quantum-Manager/tracker#87]
Due to problems with support at the same time as joomla 3 in joomla 4. We decided to remake the software architecture of the file manager. And then work on the map below.

- [x] introduce hotkey scheme
- [ ] warn about file replacement
- [ ] batch rename of files
- [ ] integrate new image editor
- [ ] adaptation for acymailing
- [ ] adaptation for helix template
- [ ] adaptation for php 8.x
- [x] adaptation for joomla 4
- [ ] partial adaptation for wordpress (light version for wordpress)
- [ ] creating a service for optimizing images
